### ISSUE TITLE
Nodecast doesn't appear as a casting device.

### ISSUE THREAD

**Issue by webdevan** [mauimauer/nodecast#14]
I am running nodecast and it says "ready to cast" yet neither my android or Chrome on Windows can detect it. I have a real Chromecast which works fine. I have noticed with the Google Cast extension, if I go to options then I can see nodecast listed under available cast devices, but I can't select it from that screen. Google cast says "No Cast devices found." when my real Chromecast is off.

**Comment by jshbrntt** [comment]
Maybe we need to unblock some ports or something?

**Comment by SAMUD** [comment]
+1 here too

**Comment by DaAwesomeRazor** [comment]
Same

**Comment by mkanet** [comment]
Same.  It's listening on port 8008.  However, not shown in the list of Casting devices on LAN; even with all ports open (no firewall) on a PC.  Is there something I'm missing?

**Comment by webdevan** [comment]
Closing this because it's 5 years old. I don't think this project is even still going.
